const productos = [
  {
    id: "exploding-kittens",
    nombre: "Exploding Kittens",
    categoria: "Cartas",
    imagen: "images/juegos/explodingkittens.webp",
    descripcion:
      "Juego de cartas divertido y caotico donde los jugadores intentan evitar explotar mientras juegan cartas para sabotear a sus oponentes.",
    precio: 16990,
    descuento: "10%",
    stock: 8,
    jugadores: "2 a 5 jugadores",
    edad: "7+ años",
    duracion: "20 minutos",
  },
  {
    id: "sushi-go",
    nombre: "Sushi Go!",
    categoria: "Cartas",
    imagen: "images/juegos/sushigo.webp",
    descripcion:
      "Juego de seleccion de cartas donde los jugadores forman combinaciones de sushi para conseguir la mayor cantidad de puntos.",
    precio: 14990,
    descuento: "15%",
    stock: 6,
    jugadores: "2 a 5 jugadores",
    edad: "8+ años",
    duracion: "15 min",
  },
  {
    id: "virus",
    nombre: "Virus!",
    categoria: "Cartas",
    imagen: "images/juegos/virus.webp",
    descripcion:
      "Juego competitivo donde cada jugador intenta completar un cuerpo sano mientras usa virus, medicinas y tratamientos contra sus rivales.",
    precio: 13990,
    descuento: "Sin descuento",
    stock: 10,
    jugadores: "2 a 6 jugadores",
    edad: "8+ años",
    duracion: "20 min",
  },
  {
    id: "pandemic",
    nombre: "Pandemic",
    categoria: "Cooperativos",
    imagen: "images/juegos/pandemic.webp",
    descripcion:
      "Juego cooperativo donde los jugadores forman un equipo de especialistas que debe contener brotes, viajar por el mundo y encontrar curas antes de que las enfermedades se propaguen sin control.",
    precio: 32990,
    descuento: "Sin descuento",
    stock: 5,
    jugadores: "2 a 4 jugadores",
    edad: "8+ años",
    duracion: "45 min",
  },
  {
    id: "the-crew",
    nombre: "The Crew",
    categoria: "Cooperativos",
    imagen: "images/juegos/thecrew.webp",
    descripcion:
      "Juego cooperativo de bazas donde los jugadores deben completar misiones espaciales comunicandose de forma limitada y jugando sus cartas en el momento correcto.",
    precio: 18990,
    descuento: "10%",
    stock: 7,
    jugadores: "3 a 5 jugadores",
    edad: "10+ años",
    duracion: "20 min",
  },
  {
    id: "codigo-secreto-duo",
    nombre: "Codigo Secreto Duo",
    categoria: "Cooperativos",
    imagen: "images/juegos/codigosecretoduo.webp",
    descripcion:
      "Version cooperativa de Codigo Secreto donde dos jugadores entregan pistas de una palabra para encontrar agentes ocultos antes de quedarse sin turnos.",
    precio: 19990,
    descuento: "15%",
    stock: 6,
    jugadores: "2+ jugadores",
    edad: "11+ años",
    duracion: "15 min",
  },
  {
    id: "catan",
    nombre: "Catan",
    categoria: "Estrategia",
    imagen: "images/juegos/catan.webp",
    descripcion:
      "Juego de estrategia y negociacion donde los jugadores recolectan recursos, construyen caminos y poblados, y compiten por desarrollar la isla de Catan.",
    precio: 34990,
    descuento: "10%",
    stock: 4,
    jugadores: "3 a 4 jugadores",
    edad: "10+ años",
    duracion: "60 min",
  },
  {
    id: "risk",
    nombre: "Risk",
    categoria: "Estrategia",
    imagen: "images/juegos/risk.webp",
    descripcion:
      "Clasico juego de conquista territorial donde los jugadores despliegan ejercitos, atacan regiones rivales y buscan dominar el mapa mediante estrategia y dados.",
    precio: 29990,
    descuento: "Sin descuento",
    stock: 3,
    jugadores: "2 a 6 jugadores",
    edad: "10+ años",
    duracion: "120 min",
  },
  {
    id: "carcassonne",
    nombre: "Carcassonne",
    categoria: "Estrategia",
    imagen: "images/juegos/carcassone.webp",
    descripcion:
      "Juego de colocacion de losetas donde los jugadores construyen ciudades, caminos y monasterios mientras ubican seguidores para conseguir puntos.",
    precio: 27990,
    descuento: "12%",
    stock: 5,
    jugadores: "2 a 5 jugadores",
    edad: "7+ años",
    duracion: "35 min",
  },
  {
    id: "uno",
    nombre: "UNO",
    categoria: "Familiares",
    imagen: "images/juegos/uno.webp",
    descripcion:
      "Juego de cartas familiar donde los jugadores deben quedarse sin cartas combinando colores, numeros y cartas especiales para cambiar el ritmo de la partida.",
    precio: 7990,
    descuento: "Sin descuento",
    stock: 12,
    jugadores: "2 a 10 jugadores",
    edad: "7+ años",
    duracion: "15 min",
  },
  {
    id: "jenga",
    nombre: "Jenga",
    categoria: "Familiares",
    imagen: "images/juegos/jenga.webp",
    descripcion:
      "Juego de habilidad donde los jugadores retiran bloques de una torre y los colocan arriba intentando que la estructura no se derrumbe.",
    precio: 12990,
    descuento: "10%",
    stock: 9,
    jugadores: "1+ jugadores",
    edad: "6+ años",
    duracion: "20 min",
  },
  {
    id: "dobble",
    nombre: "Dobble",
    categoria: "Familiares",
    imagen: "images/juegos/dobble.webp",
    descripcion:
      "Juego rapido de observacion donde los jugadores deben encontrar simbolos repetidos entre cartas antes que los demas.",
    precio: 14990,
    descuento: "15%",
    stock: 8,
    jugadores: "2 a 8 jugadores",
    edad: "6+ años",
    duracion: "10 min",
  },
];
